// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPollutionExcel(arg1:Array<main.DetectRow>):Promise<main.ExportResponse>;

export function ImportTXT():Promise<main.ImportResponse>;

export function StartDetection(arg1:main.DetectRequest):Promise<main.DetectResponse>;
