// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPollutionExcel(arg1) {
  return window['go']['main']['App']['ExportPollutionExcel'](arg1);
}

export function ImportTXT() {
  return window['go']['main']['App']['ImportTXT']();
}

export function StartDetection(arg1) {
  return window['go']['main']['App']['StartDetection'](arg1);
}
